---
- hosts: all
  become: true
  tasks:
    - name: Update system packages
      yum:
        name: '*'
        state: latest

    - name: Install Apache web server
      yum:
        name: httpd
        state: present

    - name: Start Apache service
      service:
        name: httpd
        state: started
        enabled: yes
